version: 2.1

executors:
  php7_3:
    docker:
      - image: circleci/php:7.3
  php7_2:
    docker:
      - image: circleci/php:7.2
  php7_1:
    docker:
      - image: circleci/php:7.1
      
commands:
  composer_install:
    steps:
      - checkout
      - run: php -v
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: vendor/bin/phpunit

jobs:
  php73: 
    executor: php7_3
    steps:
      - composer_install
  php72: 
    executor: php7_2
    steps:
      - composer_install
  php71: 
    executor: php7_1
    steps:
      - composer_install

workflows:
  test:
    jobs:
      - php73
      - php72
      - php71
